version: 0.0
os: linux
files:
  - source: /
    destination: $HOME/go/src/
hooks:
  BeforeInstall:
    - location: deployScripts/BeforeInstall.sh
  AfterInstall:
    - location: deployScripts/AfterInstall.sh
  ApplicationStart:
    - location: deployScripts/ApplicationStart.sh
  ValidateService:
    - location: deployScripts/ValidateService.sh
