version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/go/src/ratdevelopment/
hooks:
  BeforeInstall:
    - location: deployScripts/BeforeInstall.sh
      location: deployScripts/VerifyCassandra.sh
      runas: root
  AfterInstall:
    - location: deployScripts/InitSchema.sh
    - location: deployScripts/BuildApplication.sh
      timeout: 120
  ApplicationStart:
    - location: deployScripts/ApplicationStart.sh
  ValidateService:
    - location: deployScripts/ValidateService.sh
      timeout: 60
