version: "2.1"

services:
  cdaemon:
    image: cassandra:latest
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]

  ratdevelopment-backend:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - cdaemon:cassandra
